#ifndef __IO_CTRL_H
#define __IO_CTRL_H

#define GPIOB_RCC RCC_APB2Periph_GPIOB
#define GPIOB_PORT GPIOB
#define CHG_POWER_EN GPIO_Pin_8
#define CHG_POWER_EN_ONOFF(x) GPIO_WriteBit(GPIOB_PORT, CHG_POWER_EN, x);

#define GPIOB_RCC RCC_APB2Periph_GPIOB
#define GPIOB_PORT GPIOB
#define DSG_POWER_EN GPIO_Pin_9
#define DSG_POWER_EN_ONOFF(x) GPIO_WriteBit(GPIOB_PORT, DSG_POWER_EN, x);

#define GPIOB_RCC RCC_APB2Periph_GPIOB
#define GPIOB_PORT GPIOB
#define DISPLAY_POWER_EN GPIO_Pin_10
#define DISPLAY_POWER_EN_ONOFF(x) GPIO_WriteBit(GPIOB_PORT, DISPLAY_POWER_EN, x);

void IO_CTRL_Config(void);

#endif
